(source gnu)
(source melpa)

(depends-on "evil")
(depends-on "git-gutter")
(depends-on "monokai-theme")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "evil-leader")
(depends-on "jedi")
(depends-on "evil-surround")
(depends-on "arduino-mode")
(depends-on "evil-nerd-commenter")
(depends-on "zeal-at-point")
(depends-on "flycheck")