(require 'arduino-mode)
(require 'evil)
(require 'evil-leader)
(require 'evil-nerd-commenter)
(require 'evil-org)
(require 'flycheck)
(require 'git-gutter)
(require 'ido)
(require 'jedi)
(require 'magit)
(require 'markdown-mode)
(require 'monokai-theme)
(require 'org)
(require 'evil-surround)
(require 'tramp)
(require 'zeal-at-point)

;CONFIGS
(global-git-gutter-mode +1)
(load-theme 'monokai t)
(setq tramp-default-method "ssh")

(add-hook 'python-mode-hook 'jedi:setup)
(setq jedi:complete-on-dot t)
